twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        genre_repository: '@App\Repository\GenreRepository'
        categorie_repository: '@App\Repository\CategorieRepository'
        musique_repository: '@App\Repository\MusiqueRepository'
when@test:
    twig:
        strict_variables: true
